/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_savvasdalkitsis_multitouch_EventDispatch */

#ifndef _Included_com_savvasdalkitsis_multitouch_EventDispatch
#define _Included_com_savvasdalkitsis_multitouch_EventDispatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_savvasdalkitsis_multitouch_EventDispatch
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_savvasdalkitsis_multitouch_EventDispatch_init
  (JNIEnv *, jclass);

/*
 * Class:     com_savvasdalkitsis_multitouch_EventDispatch
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_savvasdalkitsis_multitouch_EventDispatch_start
  (JNIEnv *, jclass);

/*
 * Class:     com_savvasdalkitsis_multitouch_EventDispatch
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_savvasdalkitsis_multitouch_EventDispatch_stop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
