/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_savvasdalkitsis_mac_gestures_MacOsGestures */

#ifndef _Included_com_savvasdalkitsis_mac_gestures_MacOsGestures
#define _Included_com_savvasdalkitsis_mac_gestures_MacOsGestures
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_savvasdalkitsis_mac_gestures_MacOsGestures
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_savvasdalkitsis_mac_gestures_MacOsGestures_init
  (JNIEnv *, jclass);

/*
 * Class:     com_savvasdalkitsis_mac_gestures_MacOsGestures
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_savvasdalkitsis_mac_gestures_MacOsGestures_start
  (JNIEnv *, jclass);

/*
 * Class:     com_savvasdalkitsis_mac_gestures_MacOsGestures
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_savvasdalkitsis_mac_gestures_MacOsGestures_stop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
