/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_savvasdalkitsis_mac_gestures_MacOsGesturesNative */

#ifndef _Included_com_savvasdalkitsis_mac_gestures_MacOsGesturesNative
#define _Included_com_savvasdalkitsis_mac_gestures_MacOsGesturesNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_savvasdalkitsis_mac_gestures_MacOsGesturesNative
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_savvasdalkitsis_mac_gestures_MacOsGesturesNative_init
  (JNIEnv *, jclass, jclass);

/*
 * Class:     com_savvasdalkitsis_mac_gestures_MacOsGesturesNative
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_savvasdalkitsis_mac_gestures_MacOsGesturesNative_start
  (JNIEnv *, jclass);

/*
 * Class:     com_savvasdalkitsis_mac_gestures_MacOsGesturesNative
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_savvasdalkitsis_mac_gestures_MacOsGesturesNative_stop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
